% PLEASE DOWNLOAD THE MATLAB GRAPH LIBRARY FROMTHE SITE GIVEN BELOW
% http://dgleich.github.com/matlab-bgl/
% RUN GRAPH_GEN FILE WITH NAME OF THE FILE AS INPUT
% IT WILL GENERATE THE NECESSARY DATA STRUCTURES FOR SIMULATION

% FOR INDEPENDENT CASCADE RUN INDEPENDENT_CASCADE(p) FILE p IS THE CASCADE
% PROBABILITY
% FOR LINEAR THRESHOLD RUN LINEAR_THRESHOLD(LT) LT can have three values
% 'HighDeg' 'Central' and 'Random'

% FOR WEIGHTED CASCADE RUN WEIGHTED_CASCADE FILE . IT DOES NOT REQUIRE ANY
% INPUT